name: Deploy main branch
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com
          scope: '@jonlimcs'

      - name: Install node_modules
        run: npm ci

      if: github.ref_type == 'tag'
        - name: Serverless AWS Authentication Production
        run: npx sls config credentials --provider aws --key ${{ secrets.PROD_AWS_KEY }} --secret ${{ secrets.PROD_AWS_SECRET }}
        - name: Deploy Production Server
          run: npm run deploy-server --region=us-east-1
        if: github.ref_type == 'branch'
        - name: Serverless AWS Authentication Development
        run: npx sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_KEY }}
        - name: Deploy Development Server
          run: npm run deploy-server --region-ap-southeast-1